import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primitives Colors
        primary: {
          50: "var(--color-primitive-primary-50)",
          100: "var(--color-primitive-primary-100)",
          200: "var(--color-primitive-primary-200)",
          300: "var(--color-primitive-primary-300)",
          400: "var(--color-primitive-primary-400)",
          500: "var(--color-primitive-primary-500)",
          600: "var(--color-primitive-primary-600)",
          700: "var(--color-primitive-primary-700)",
          800: "var(--color-primitive-primary-800)",
          900: "var(--color-primitive-primary-900)",
          950: "var(--color-primitive-primary-950)",
        },
        secondary: {
          50: "var(--color-primitive-secondary-50)",
          100: "var(--color-primitive-secondary-100)",
          200: "var(--color-primitive-secondary-200)",
          300: "var(--color-primitive-secondary-300)",
          400: "var(--color-primitive-secondary-400)",
          500: "var(--color-primitive-secondary-500)",
          600: "var(--color-primitive-secondary-600)",
          700: "var(--color-primitive-secondary-700)",
          800: "var(--color-primitive-secondary-800)",
          900: "var(--color-primitive-secondary-900)",
          950: "var(--color-primitive-secondary-950)",
        },
        neutral: {
          50: "var(--color-primitive-neutral-50)",
          100: "var(--color-primitive-neutral-100)",
          200: "var(--color-primitive-neutral-200)",
          300: "var(--color-primitive-neutral-300)",
          400: "var(--color-primitive-neutral-400)",
          500: "var(--color-primitive-neutral-500)",
          600: "var(--color-primitive-neutral-600)",
          700: "var(--color-primitive-neutral-700)",
          800: "var(--color-primitive-neutral-800)",
          900: "var(--color-primitive-neutral-900)",
          950: "var(--color-primitive-neutral-950)",
        },
        accent: {
          50: "var(--color-primitive-accent-50)",
          100: "var(--color-primitive-accent-100)",
          200: "var(--color-primitive-accent-200)",
          300: "var(--color-primitive-accent-300)",
          400: "var(--color-primitive-accent-400)",
          500: "var(--color-primitive-accent-500)",
          600: "var(--color-primitive-accent-600)",
          700: "var(--color-primitive-accent-700)",
          800: "var(--color-primitive-accent-800)",
          900: "var(--color-primitive-accent-900)",
          950: "var(--color-primitive-accent-950)",
        },
        success: {
          50: "var(--color-primitive-success-50)",
          100: "var(--color-primitive-success-100)",
          200: "var(--color-primitive-success-200)",
          300: "var(--color-primitive-success-300)",
          400: "var(--color-primitive-success-400)",
          500: "var(--color-primitive-success-500)",
          600: "var(--color-primitive-success-600)",
          700: "var(--color-primitive-success-700)",
          800: "var(--color-primitive-success-800)",
          900: "var(--color-primitive-success-900)",
          950: "var(--color-primitive-success-950)",
        },
        warning: {
          50: "var(--color-primitive-warning-50)",
          100: "var(--color-primitive-warning-100)",
          200: "var(--color-primitive-warning-200)",
          300: "var(--color-primitive-warning-300)",
          400: "var(--color-primitive-warning-400)",
          500: "var(--color-primitive-warning-500)",
          600: "var(--color-primitive-warning-600)",
          700: "var(--color-primitive-warning-700)",
          800: "var(--color-primitive-warning-800)",
          900: "var(--color-primitive-warning-900)",
          950: "var(--color-primitive-warning-950)",
        },
        error: {
          50: "var(--color-primitive-error-50)",
          100: "var(--color-primitive-error-100)",
          200: "var(--color-primitive-error-200)",
          300: "var(--color-primitive-error-300)",
          400: "var(--color-primitive-error-400)",
          500: "var(--color-primitive-error-500)",
          600: "var(--color-primitive-error-600)",
          700: "var(--color-primitive-error-700)",
          800: "var(--color-primitive-error-800)",
          900: "var(--color-primitive-error-900)",
          950: "var(--color-primitive-error-950)",
        },
        // Semantic Colors
        "bg-primary": "var(--color-background-primary)",
        "bg-secondary": "var(--color-background-secondary)",
        "bg-neutral": "var(--color-background-neutral)",
        "bg-surface": "var(--color-background-surface)",
        "bg-surface-elevated": "var(--color-background-surfaceElevated)",
        "bg-inverse": "var(--color-background-inverse)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "text-disabled": "var(--color-text-disabled)",
        "text-inverse": "var(--color-text-inverse)",
        "text-link": "var(--color-text-link)",
        "text-link-hover": "var(--color-text-linkHover)",
        "border-default": "var(--color-border-default)",
        "border-subtle": "var(--color-border-subtle)",
        "border-focus": "var(--color-border-focus)",
        "border-error": "var(--color-border-error)",
        "border-success": "var(--color-border-success)",
        "interactive-primary": "var(--color-interactive-primary)",
        "interactive-primary-hover": "var(--color-interactive-primaryHover)",
        "interactive-primary-active": "var(--color-interactive-primaryActive)",
        "interactive-secondary": "var(--color-interactive-secondary)",
        "interactive-secondary-hover": "var(--color-interactive-secondaryHover)",
        "interactive-secondary-active": "var(--color-interactive-secondaryActive)",
        "interactive-disabled": "var(--color-interactive-disabled)",
      },
      fontFamily: {
        primary: "var(--typography-primitive-font-family-primary)",
        secondary: "var(--typography-primitive-font-family-secondary)",
        mono: "var(--typography-primitive-font-family-mono)",
      },
      fontSize: {
        xs: "var(--typography-primitive-font-size-xs)",
        sm: "var(--typography-primitive-font-size-sm)",
        base: "var(--typography-primitive-font-size-base)",
        lg: "var(--typography-primitive-font-size-lg)",
        xl: "var(--typography-primitive-font-size-xl)",
        "2xl": "var(--typography-primitive-font-size-2xl)",
        "3xl": "var(--typography-primitive-font-size-3xl)",
        "4xl": "var(--typography-primitive-font-size-4xl)",
        "5xl": "var(--typography-primitive-font-size-5xl)",
        "6xl": "var(--typography-primitive-font-size-6xl)",
      },
      spacing: {
        ...Object.fromEntries(
          Object.entries({
            0: "var(--spacing-primitive-0)",
            1: "var(--spacing-primitive-1)",
            2: "var(--spacing-primitive-2)",
            3: "var(--spacing-primitive-3)",
            4: "var(--spacing-primitive-4)",
            5: "var(--spacing-primitive-5)",
            6: "var(--spacing-primitive-6)",
            8: "var(--spacing-primitive-8)",
            10: "var(--spacing-primitive-10)",
            12: "var(--spacing-primitive-12)",
            16: "var(--spacing-primitive-16)",
            20: "var(--spacing-primitive-20)",
            24: "var(--spacing-primitive-24)",
            32: "var(--spacing-primitive-32)",
            40: "var(--spacing-primitive-40)",
            48: "var(--spacing-primitive-48)",
            56: "var(--spacing-primitive-56)",
            64: "var(--spacing-primitive-64)",
          })
        ),
      },
      borderRadius: {
        none: "var(--radius-primitive-none)",
        sm: "var(--radius-primitive-sm)",
        base: "var(--radius-primitive-base)",
        md: "var(--radius-primitive-md)",
        lg: "var(--radius-primitive-lg)",
        xl: "var(--radius-primitive-xl)",
        "2xl": "var(--radius-primitive-2xl)",
        "3xl": "var(--radius-primitive-3xl)",
        full: "var(--radius-primitive-full)",
      },
      boxShadow: {
        xs: "var(--shadow-primitive-xs)",
        sm: "var(--shadow-primitive-sm)",
        base: "var(--shadow-primitive-base)",
        md: "var(--shadow-primitive-md)",
        lg: "var(--shadow-primitive-lg)",
        xl: "var(--shadow-primitive-xl)",
        "2xl": "var(--shadow-primitive-2xl)",
        inner: "var(--shadow-primitive-inner)",
        none: "var(--shadow-primitive-none)",
      },
      transitionDuration: {
        fast: "var(--motion-primitive-duration-fast)",
        base: "var(--motion-primitive-duration-base)",
        slow: "var(--motion-primitive-duration-slow)",
        slower: "var(--motion-primitive-duration-slower)",
        slowest: "var(--motion-primitive-duration-slowest)",
      },
      transitionTimingFunction: {
        "ease-in": "var(--motion-primitive-easing-easeIn)",
        "ease-out": "var(--motion-primitive-easing-easeOut)",
        "ease-in-out": "var(--motion-primitive-easing-easeInOut)",
        linear: "var(--motion-primitive-easing-linear)",
      },
    },
  },
  plugins: [],
};
export default config;

