/**
 * CSS Generation Script
 * 
 * Generates CSS files from design tokens.
 * Run this script to update CSS variables.
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { generateCSSVariables, generateResponsiveTypographyCSS } from './css-variables';

const outputDir = join(process.cwd(), 'app');

// Generate CSS variables
const cssVariables = generateCSSVariables();
const responsiveTypography = generateResponsiveTypographyCSS();

// Combine into single CSS file
const cssContent = `/* Design Tokens - Auto-generated */
/* Do not edit this file directly. Edit tokens in /tokens directory instead. */

${cssVariables}

/* Responsive Typography Classes */
${responsiveTypography}
`;

writeFileSync(join(outputDir, 'tokens.css'), cssContent, 'utf-8');

console.log('✅ Design tokens CSS generated successfully!');
console.log('📁 Output: app/tokens.css');

